name: evento

services:
  backend:
    build: ./
    container_name: hcmc-backend
    command: sh -c "pwd && ls -la && cd /backend/app && python -m uvicorn main:app --reload --host=0.0.0.0 --workers=4"
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app  # Mount application code only
      - ./backend:/db
    environment:
      - PYTORCH_CUDA_VISIBLE_DEVICES=0  # Assuming you have one GPU

  nginx: 
    build